const exchangeTypes = {
	ADD_TO_EXCHANGE: 'ADD_TO_EXCHANGE',
	REMOVE_EXCHANGE_ITEM: 'REMOVE_EXCHANGE_ITEM',
	CONFIRM_EXCHANGE_START: 'CONFIRM_EXCHANGE_START',
	CONFIRM_RECEPTION_START: 'CONFIRM_RECEPTION_START',
	RELOAD_EXCHANGE_STATE: 'RELOAD_EXCHANGE_STATE',
	SET_EXCHANGE: 'SET_EXCHANGE',
};

export default exchangeTypes;
